import os
import base64
import io
from PIL import Image, ImageDraw, ImageFont

# This script generates all required assets programmatically and embeds them into a new Python file.
OUTPUT_FILE = "_assets.py"

def create_reddit_template_image():
    """Creates the exact Reddit post template from the reference image using Pillow."""
    img = Image.new('RGB', (1080, 550), color='#FFFFFF')
    draw = ImageDraw.Draw(img)

    # Rounded rectangle background
    draw.rounded_rectangle(((20, 20), (1060, 530)), fill="#FFFFFF", outline="#E0E2E3", width=2, radius=16)

    # Header section
    icon_bg = Image.new('RGBA', (60, 60), (0,0,0,0))
    icon_draw = ImageDraw.Draw(icon_bg)
    icon_draw.ellipse([(0,0), (59,59)], fill='#FF4500')
    img.paste(icon_bg, (40, 40), icon_bg)
    
    # Placeholder for a verified tick
    tick_bg = Image.new('RGBA', (24, 24), (0,0,0,0))
    tick_draw = ImageDraw.Draw(tick_bg)
    tick_draw.ellipse([(0,0), (23,23)], fill='#1D9BF0')
    tick_draw.polygon([(6,12), (10,16), (18,8)], fill='white')
    img.paste(tick_bg, (235, 48), tick_bg)

    # Placeholder for awards (small colored squares)
    draw.rectangle(((265, 52), (280, 67)), fill='#54B7D5')
    draw.rectangle(((285, 52), (300, 67)), fill='#E8B22B')
    draw.rectangle(((305, 52), (320, 67)), fill='#d7d7d7')

    # Footer Icons (simplified representations)
    # Likes Icon
    draw.arc(((60, 470), (100, 510)), 180, 0, fill='#636466', width=4)
    draw.line(((60, 490), (45, 475), (80, 450), (115, 475), (100, 490)), fill='#636466', width=4, join='round')
    # Comments Icon
    draw.rounded_rectangle(((220, 470), (280, 505)), radius=6, outline='#636466', width=4)

    # Return the image object
    return img

def encode_image_to_base64(img_object):
    """Encodes a Pillow Image object into a Base64 string."""
    buffered = io.BytesIO()
    img_object.save(buffered, format="PNG")
    return base64.b64encode(buffered.getvalue()).decode('utf-8')

# --- MAIN EXECUTION ---
if __name__ == "__main__":
    print("--- Generating Reddit Template Image ---")
    reddit_template_obj = create_reddit_template_image()
    
    print("--- Encoding Asset to Base64 ---")
    reddit_b64 = encode_image_to_base64(reddit_template_obj)

    print(f"--- Writing Embedded Asset File: {OUTPUT_FILE} ---")
    output_content = [
        "# This file is auto-generated by generate_and_embed_assets.py. DO NOT EDIT.",
        "# It contains all necessary image assets as Base64 strings.",
        "ASSET_DATA = {",
        f"    'reddit_template.png': '{reddit_b64}'",
        "}"
    ]

    with open(OUTPUT_FILE, "w") as f:
        f.write("\n".join(output_content))

    print(f"\nSUCCESS: Created '{OUTPUT_FILE}'.")
    print("You MUST now commit this new file to your Git repository before deploying.")
