# The final, most robust blueprint for the AI Video Generator.
# This version explicitly defines environment variables for each service
# to prevent any parsing errors.

services:
  # 1. The Web Service (The "Waiter")
  - type: web
    name: ai-video-web
    env: python
    healthCheckPath: /health
    # Common build/start commands and env vars for this service
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      # Secrets that you will set in the Render dashboard
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      # This tells our Python app how to find the Redis queue
      - key: REDIS_URL
        fromService:
          type: redis
          name: ai-video-queue
          property: connectionString

  # 2. The Background Worker (The "Kitchen")
  - type: worker
    name: ai-video-worker
    env: python
    # Common build/start commands and env vars for this service
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -m worker"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      # Secrets that you will set in the Render dashboard
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      # This tells our Python app how to find the Redis queue
      - key: REDIS_URL
        fromService:
          type: redis
          name: ai-video-queue
          property: connectionString

  # 3. The Redis Queue (The "Order Queue")
  - type: redis
    name: ai-video-queue
    plan: free
    maxmemoryPolicy: allkeys-lru
