services:
  - type: web
    name: makeaclip-web
    env: python
    # This tells Render to run our build script before starting the server
    buildCommand: "./build.sh"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: /health
    plan: free # Or your preferred instance type
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: REDIS_URL
        fromService:
          type: redis
          name: makeaclip-redis
          property: connectionString
      # All your secrets from the Render dashboard will be available here
      - key: AUTH0_DOMAIN
        sync: false
      - key: AUTH0_CLIENT_ID
        sync: false
      - key: AUTH0_CLIENT_SECRET
        sync: false
      - key: APP_SECRET_KEY
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

  - type: worker
    name: makeaclip-worker
    env: python
    # The worker also needs the same build process
    buildCommand: "./build.sh"
    startCommand: "python worker.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: REDIS_URL
        fromService:
          type: redis
          name: makeaclip-redis
          property: connectionString
      # All secrets the worker needs to perform its tasks
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

  - type: redis
    name: makeaclip-redis
    plan: free
    maxmemoryPolicy: allkeys-lru
    ipAllowList: [] # Keep empty to allow access from other Render services
