# The final, correct blueprint using a decoupled architecture.

services:
  # 1. The Web Service
  - type: web
    name: ai-video-web
    env: python
    healthCheckPath: /health
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: ai-video-queue
          property: connectionString

  # 2. The Background Worker
  - type: worker
    name: ai-video-worker
    env: python
    buildCommand: "pip install -r requirements.txt"
    # THIS IS THE KEY FIX: We use the official rq worker command
    # The --preload flag tells the worker to load our tasks.py file at startup.
    startCommand: "rq worker --preload tasks default"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: ai-video-queue
          property: connectionString

  # 3. The Redis Queue
  - type: redis
    name: ai-video-queue
    plan: free
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []
