services:
  - type: web
    name: makeaclip-web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: /health
    # This is the critical fix for the ImageMagick error
    nativeEnvironment:
      systemPackages:
        - imagemagick
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: REDIS_URL
        fromService:
          type: redis
          name: makeaclip-redis
          property: connectionString
      - key: AUTH0_DOMAIN
        sync: false
      - key: AUTH0_CLIENT_ID
        sync: false
      - key: AUTH0_CLIENT_SECRET
        sync: false
      - key: APP_SECRET_KEY
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

  - type: worker
    name: makeaclip-worker
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python worker.py"
    nativeEnvironment:
      systemPackages:
        - imagemagick
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: REDIS_URL
        fromService:
          type: redis
          name: makeaclip-redis
          property: connectionString
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

  - type: redis
    name: makeaclip-redis
    plan: free
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []
