services:
  - type: web
    name: makeaclip-web
    env: python
    # THE FIX: Use a python script for the build command
    buildCommand: "python build.py"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: REDIS_URL
        fromService:
          type: redis
          name: makeaclip-redis
          property: connectionString
      # All your secrets are synced from your Render dashboard
      - key: AUTH0_DOMAIN
        sync: false
      - key: AUTH0_CLIENT_ID
        sync: false
      - key: AUTH0_CLIENT_SECRET
        sync: false
      - key: APP_SECRET_KEY
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

  - type: worker
    name: makeaclip-worker
    env: python
    # THE FIX: Use a python script for the build command
    buildCommand: "python build.py"
    startCommand: "python worker.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: REDIS_URL
        fromService:
          type: redis
          name: makeaclip-redis
          property: connectionString
      # All secrets the worker needs to perform its tasks
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

  - type: redis
    name: makeaclip-redis
    plan: free
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []
