services:
  # 1. The Web Service
  - type: web
    name: ai-video-web
    env: python
    healthCheckPath: /health
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: AUTH0_DOMAIN
        value: "dev-23iqnnqsp0tbnxch.us.auth0.com" # Storing as plain text is fine for the domain
      - key: AUTH0_CLIENT_ID
        value: "99E30sRywMn8h4uFwa5edAbR27F6NGzU"  # Storing as plain text is fine for the client ID
      - key: AUTH0_CLIENT_SECRET
        sync: false # This is a secret
      - key: APP_SECRET_KEY
        sync: false # This is a secret
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: ai-video-queue
          property: connectionString

  # 2. The Background Worker
  - type: worker
    name: ai-video-worker
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python worker.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: ai-video-queue
          property: connectionString

  # 3. The Redis Queue
  - type: redis
    name: ai-video-queue
    plan: free
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []
