services:
  # 1. The Web Service
  - type: web
    name: ai-video-web
    env: python
    healthCheckPath: /health
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: AUTH0_DOMAIN
        sync: false
      - key: AUTH0_CLIENT_ID
        sync: false
      - key: AUTH0_CLIENT_SECRET
        sync: false
      - key: APP_SECRET_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: ai-video-queue
          property: connectionString
      - key: HCTI_USER_ID
        sync: false # Web service might need it later
      - key: HCTI_API_KEY
        sync: false # Web service might need it later

  # 2. The Background Worker
  - type: worker
    name: ai-video-worker
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python worker.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: REDIS_URL
        fromService:
          type: redis
          name: ai-video-queue
          property: connectionString
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      # --- THE FIX: ADDING THE MISSING SECRETS TO THE WORKER ---
      - key: HCTI_USER_ID
        sync: false
      - key: HCTI_API_KEY
        sync: false

  # 3. The Redis Queue
  - type: redis
    name: ai-video-queue
    plan: free
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []
