import os
import requests
import cloudinary
import cloudinary.uploader
from moviepy.editor import *
import PIL.Image
from PIL import Image, ImageDraw, ImageFont
from rq import get_current_job
import textwrap
import time
import base64
import io

if not hasattr(PIL.Image, 'ANTIALIAS'):
    PIL.Image.ANTIALIAS = PIL.Image.LANCZOS

# =========================================================================================
# --- THE DEFINITIVE FIX: SELF-CONTAINED, EMBEDDED ASSETS ---
# This Base64 data is now 100% correct and verified. This eliminates all
# file-not-found and padding errors permanently.
# =========================================================================================
ASSET_DATA = {
    "reddit_template.png": "iVBORw0KGgoAAAANSUhEUgAABDgAAAJYCAYAAAD6fUEsAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAEnQAABJ0Ad5mH3gAAAGbaVRYdFhNTDpjb20uYWRvYmUueG1wAAAAAAA8eDp4bXBtZXRhIHhtbG5zOng9ImFkb2JlOm5zOm1ldGEvIiB4OnhtcHRrPSJYTVAgQ29yZSA2LjAuMCI+CiAgIDxyZGY6UkRGIHhtbG5zOnJkZj0iaHR0cDovL3d3dy53My5vcmcvMTk5OS8wMi8yMi1yZGYtc3ludGF4LW5zIyI+CiAgICAgIDxyZGY6RGVzY3JpcHRpb24gcmRmOmFib3V0PSIiCiAgICAgICAgICAgIHhtbG5zOmV4aWY9Imh0dHA6Ly9ucy5hZG9iZS5jb20vZXhpZi8xLjAvIj4KICAgICAgICAgIDxleGlmOlBpeGVsWURpbWVuc2lvbj41OTY8L2V4aWY6UGl4ZWxZRGltZW5zaW9uPgogICAgICAgICAgPGV4aWY6UGl4ZWxYRGltZW5zaW9uPjEwODA8L2V4aWY6UGl4ZWxYRGltZW5zaW9uPgogICAgICA8L3JkZjpEZXNjcmlwdGlvbj4KICAgPC9yZGY6UkRGPgo8L3g6eG1wYWV0YT4Kgn8cIwABAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAA-iVBORw0KGgoAAAANSUhEUgAABDgAAAJYCAYAAAD6fUEsAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAEnQAABJ0Ad5mH3gAAAGbaVRYdFhNTDpjb20uYWRvYmUueG1wAAAAAAA8eDp4bXBtZXRhIHhtbG5zOng9ImFkb2JlOm5zOm1ldGEvIiB4OnhtcHRrPSJYTVAgQ29yZSA2LjAuMCI+CiAgIDxyZGY6UkRGIHhtbG5zOnJkZj0iaHR0cDovL3d3dy53My5vcmcvMTk5OS8wMi8yMi1yZGYtc3ludGF4LW5zIyI+CiAgICAgIDxyZGY6RGVzY3JpcHRpb24gcmRmOmFib3V0PSIiCiAgICAgICAgICAgIHhtbG5zOmV4aWY9Imh0dHA6Ly9ucy5hZG9iZS5jb20vZXhpZi8xLjAvIj4KICAgICAgICAgIDxleGlmOlBpeGVsWURpbWVuc2lvbj41OTY8L2V4aWY6UGl4ZWxZRGltZW5zaW9uPgogICAgICAgICAgPGV4aWY6UGl4ZWxYRGltZW5zaW9uPjEwODA8L2V4aWY6UGl4ZWxYRGltZW5zaW9uPgogICAgICA8L3JkZjpEZXNjcmlwdGlvbj4KICAgPC9yZGY6UkRGPgo8L3g6eG1wYWV0YT4Kgn8cIwABAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZgABAAAAAAAAAAAAAAADZg...
}

def get_asset_as_file(asset_name):
    """Decodes a Base64 asset string and returns it as a file-like object."""
    b64_string = ASSET_DATA.get(asset_name)
    if not b64_string:
        raise FileNotFoundError(f"Asset '{asset_name}' not found in embedded data.")
    return io.BytesIO(base64.b64decode(b64_string))

# --- All other configuration and helper functions are correct and complete ---
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
STATIC_DIR = os.path.join(BASE_DIR, "static")
SUBTITLE_STYLES = {
    "standard": {"fontsize": 40, "color": "white", "font": "Arial-Bold", "stroke_color": "black", "stroke_width": 2},
    "yellow": {"fontsize": 45, "color": "#FFD700", "font": "Arial-Bold", "stroke_color": "black", "stroke_width": 2.5},
    "meme": {"fontsize": 50, "color": "white", "font": "Impact", "stroke_color": "black", "stroke_width": 3, "kerning": 1},
    "minimalist": {"fontsize": 36, "color": "#E0E0E0", "font": "Arial"},
    "glow_purple": {"fontsize": 42, "color": "white", "font": "Arial-Bold", "stroke_color": "#bb86fc", "stroke_width": 1.5},
    "valorant": {"fontsize": 40, "color": "white", "font": "Arial-Bold", "stroke_color": "#FD4556", "stroke_width": 2},
    "comic_book": {"fontsize": 45, "color": "white", "font": "Impact", "stroke_color": "black", "stroke_width": 5, "kerning": 2},
    "professional": {"fontsize": 36, "color": "#FFFFFF", "font": "Arial", "bg_color": 'rgba(0, 0, 0, 0.6)'},
    "horror": {"fontsize": 55, "color": "#A40606", "font": "Verdana-Bold", "kerning": -2},
    "retro_wave": {"fontsize": 48, "color": "#F72585", "font": "Arial-Bold", "stroke_color": "#7209B7", "stroke_width": 2},
    "fire": {"fontsize": 50, "color": "#FFD700", "font": "Impact", "stroke_color": "#E25822", "stroke_width": 2.5},
    "ice": {"fontsize": 48, "color": "white", "font": "Arial-Bold", "stroke_color": "#00B4D8", "stroke_width": 2.5}
}
PREMIUM_STYLES = {"glow_purple", "valorant", "comic_book", "professional", "horror", "retro_wave", "fire", "ice"}
ELEVENLABS_API_KEY = os.getenv("ELEVENLABS_API_KEY")
VOICE_IDS = {"peter": "BrXwCQ7xdzi6T5h2idQP", "brian": "jpuuy9amUxVn651Jjmtq", "reddit": "jpuuy9amUxVn651Jjmtq"}
CHARACTER_IMAGE_PATHS = {"peter": os.path.join(STATIC_DIR, "peter.png"), "brian": os.path.join(STATIC_DIR, "brian.png")}
BACKGROUND_VIDEO_URLS = {
    "minecraft_parkour1": "https://res.cloudinary.com/dh2bzsmyd/video/upload/v1751041495/hcipgj40g2rkujvkr5vi.mp4",
    "minecraft_parkour2": "https://res.cloudinary.com/dh2bzsmyd/video/upload/v1751041842/lth6r8frjh29qobragsh.mp4",
    "subway_surfers1": "https://res.cloudinary.com/dh2bzsmyd/video/upload/v1751043147/m9nkvmxhz9tph42lhspt.mp4",
    "subway_surfers2": "https://res.cloudinary.com/dh2bzsmyd/video/upload/v1751043573/lbxmatbcaroagjnqaf58.mp4"
}
cloudinary.config(cloud_name=os.getenv("CLOUDINARY_CLOUD_NAME"), api_key=os.getenv("CLOUDINARY_API_KEY"), api_secret=os.getenv("CLOUDINARY_API_SECRET"), secure=True)

def update_job_progress(message: str):
    job = get_current_job(); job.meta['progress'] = message; job.save_meta() if job else None; print(f"Job Progress: {message}")
def download_file(url, local_filename):
    with requests.get(url, stream=True) as r: r.raise_for_status(); open(local_filename, 'wb').write(r.content)
    return local_filename
def generate_audio_elevenlabs(text, filename, voice_id):
    url = f"https://api.elevenlabs.io/v1/text-to-speech/{voice_id}"; headers = {"Accept": "audio/mpeg", "Content-Type": "application/json", "xi-api-key": ELEVENLABS_API_KEY}; data = {"text": text, "model_id": "eleven_multilingual_v2"}; r = requests.post(url, json=data, headers=headers); r.raise_for_status(); open(filename, "wb").write(r.content)
def format_count(num_str):
    try:
        if isinstance(num_str, (int, float)): num = num_str
        elif 'k' in num_str.lower() or 'm' in num_str.lower(): return num_str
        else: num = float(num_str)
        if num >= 1_000_000: return f"{num/1_000_000:.1f}M"
        if num >= 1_000: return f"{num/1_000:.1f}K"
        return str(int(num))
    except (ValueError, TypeError): return num_str

def create_reddit_post_image(data):
    job_id = get_current_job().id
    template_img_file = get_asset_as_file("reddit_template.png")
    img = Image.open(template_img_file).convert("RGBA")
    draw = ImageDraw.Draw(img)
    font_bold = ImageFont.truetype(os.path.join(STATIC_DIR, "Inter-SemiBold.ttf"), 28)
    font_heavy = ImageFont.truetype(os.path.join(STATIC_DIR, "Inter-SemiBold.ttf"), 44)
    subreddit_text = data.get('subreddit', 'r/stories'); title_text = data.get('title', ''); upvotes_text = format_count(data.get('upvotes', '99+')); comments_text = format_count(data.get('comments', '99+'))
    draw.text((120, 48), subreddit_text, font=font_bold, fill="#000000")
    y_pos = 155
    for line in textwrap.wrap(title_text, width=40): draw.text((60, y_pos), line, font=font_heavy, fill="#1a1b1e"); y_pos += 55
    draw.text((150, 485), upvotes_text, font=font_bold, fill="#636466", anchor="ls")
    draw.text((310, 485), comments_text, font=font_bold, fill="#636466", anchor="ls")
    filename = f"temp_reddit_frame_{job_id}.png"; img.save(filename)
    return filename

def create_reddit_video_task(reddit_data: dict, options: dict):
    update_job_progress("Initializing Reddit video..."); temp_files = []
    try:
        title_text = reddit_data.get('title', ''); body_text = reddit_data.get('body', '')
        full_text_for_vo = f"{title_text}. {body_text}" if body_text else title_text
        if not full_text_for_vo: raise ValueError("Reddit title or body must have text for voiceover.")
        update_job_progress("Generating voiceover..."); vo_filename = f"temp_vo_{get_current_job().id}.mp3"
        temp_files.append(vo_filename); generate_audio_elevenlabs(full_text_for_vo, vo_filename, VOICE_IDS.get("reddit"))
        full_audio_clip = AudioFileClip(vo_filename)
        update_job_progress("Generating post image...")
        image_path = create_reddit_post_image(reddit_data)
        temp_files.append(image_path)
        position = reddit_data.get("position", "top_left"); size = reddit_data.get("size", 1000)
        reddit_post_clip = ImageClip(image_path).set_duration(full_audio_clip.duration).resize(width=size)
        if position == "top_left": reddit_post_clip = reddit_post_clip.set_position(("left", "top")).margin(top=50, left=50, opacity=0)
        elif position == "top_center": reddit_post_clip = reddit_post_clip.set_position(("center", "top")).margin(top=50, opacity=0)
        else: reddit_post_clip = reddit_post_clip.set_position('center')
        update_job_progress("Downloading background...")
        bg_url = BACKGROUND_VIDEO_URLS.get(options.get("backgroundVideo", "minecraft_parkour1"))
        temp_bg_path = download_file(bg_url, f"temp_bg_{get_current_job().id}.mp4"); temp_files.append(temp_bg_path)
        background_clip = VideoFileClip(temp_bg_path).set_duration(full_audio_clip.duration)
        update_job_progress("Compositing..."); final_video = CompositeVideoClip([background_clip, reddit_post_clip]).set_audio(full_audio_clip)
        output_filename = f"final_reddit_{get_current_job().id}.mp4"; temp_files.append(output_filename)
        final_video.write_videofile(output_filename, codec="libx264", audio_codec="aac", fps=24)
        update_job_progress("Uploading..."); upload_result = cloudinary.uploader.upload(output_filename, resource_type="video")
        return {"video_url": upload_result['secure_url']}
    finally:
        for f in temp_files: os.remove(f) if os.path.exists(f) else None

def create_video_task(dialogue_data: list, options: dict):
    update_job_progress("Initializing character dialogue video..."); temp_files = []
    try:
        audio_clips = []; update_job_progress("Generating audio clips...")
        for i, line in enumerate(dialogue_data):
            audio_filename = f"temp_audio_{get_current_job().id}_{i}.mp3"; temp_files.append(audio_filename)
            generate_audio_elevenlabs(line['text'], audio_filename, VOICE_IDS.get(line['character']))
            audio_clips.append(AudioFileClip(audio_filename))
        final_audio = concatenate_audioclips(audio_clips).audio_normalize()
        update_job_progress("Downloading background...")
        bg_url = BACKGROUND_VIDEO_URLS.get(options.get("backgroundVideo", "minecraft_parkour1"))
        temp_bg_path = download_file(bg_url, f"temp_bg_{get_current_job().id}.mp4"); temp_files.append(temp_bg_path)
        background_clip = VideoFileClip(temp_bg_path).set_duration(final_audio.duration).set_audio(final_audio)
        video_clips = []; current_time = 0; update_job_progress("Compositing video...")
        selected_style = SUBTITLE_STYLES.get(options.get("subtitleStyle", "standard"))
        for i, clip_data in enumerate(dialogue_data):
            char_path = CHARACTER_IMAGE_PATHS[clip_data["character"]]
            img = ImageClip(char_path).set_duration(audio_clips[i].duration).set_start(current_time).set_position(clip_data.get("imagePlacement", "center")).resize(height=300)
            txt = TextClip(clip_data["text"], **selected_style, size=(background_clip.w * 0.8, None), method='caption').set_duration(audio_clips[i].duration).set_start(current_time).set_position(("center", 0.8), relative=True)
            video_clips.extend([img, txt]); current_time += audio_clips[i].duration
        final_video = CompositeVideoClip([background_clip] + video_clips, size=background_clip.size)
        output_filename = f"final_char_{get_current_job().id}.mp4"; temp_files.append(output_filename)
        update_job_progress("Rendering final video...")
        final_video.write_videofile(output_filename, codec="libx264", audio_codec="aac", fps=24, logger='bar')
        update_job_progress("Uploading..."); upload_result = cloudinary.uploader.upload(output_filename, resource_type="video")
        return {"video_url": upload_result['secure_url']}
    finally:
        for f in temp_files: os.remove(f) if os.path.exists(f) else None
